"""
Content Agent — prepares YouTube, store listing, and content package assets.
Template-based for MVP.
"""

from pathlib import Path
from backend.agents.base_agent import BaseAgent

GAMES_DIR = Path(__file__).parent.parent.parent / "games"


def _generate_content_package(game_name: str, genre: str | None) -> str:
    genre_label = genre.title() if genre else "Casual"
    slug = game_name.lower().replace(" ", "-")

    return f"""# Content Package: {game_name}

**Generated by:** Content Agent (template-based)
**Status:** Draft — awaiting human review

---

## 1. YouTube Long-Form Video

**Title options (EN):**
1. I Made a Mobile Game in 7 Days — {game_name} Devlog
2. Building {game_name}: A {genre_label} Mobile Game From Scratch
3. {game_name} — Full Solo Dev Journey (Idea to Publish)

**Title options (TR):**
1. 7 Günde Mobil Oyun Yaptım — {game_name} Devlog
2. {game_name}: Sıfırdan {genre_label} Mobil Oyun Yapımı
3. {game_name} — Fikir'den Yayına Solo Geliştirme Süreci

**Video Outline:**
- 00:00 Intro — What is this game?
- 01:00 Game idea and design decisions
- 03:00 Unity setup and first prototype
- 06:00 Core mechanic implementation
- 10:00 Visual polish and juice
- 14:00 Playtesting and iteration
- 17:00 Store listing and publishing
- 19:00 Lessons learned + what's next

**Target length:** 18–22 minutes

---

## 2. Short-Form Content Plan

| # | Platform             | Concept                                           | Hook                                          |
|---|----------------------|---------------------------------------------------|-----------------------------------------------|
| 1 | TikTok/Reels/Shorts  | "I built this game in 7 days"                    | Show finished gameplay in first 2 seconds     |
| 2 | TikTok/Reels/Shorts  | Before/after: first prototype vs final game      | Split screen comparison                       |
| 3 | TikTok/Reels/Shorts  | The hardest bug I fixed                          | Relatable dev struggle                        |
| 4 | TikTok/Reels/Shorts  | "Would you play this?" — gameplay loop showcase  | Direct audience question                      |
| 5 | TikTok/Reels/Shorts  | "Day 1 vs Day 7" timelapse                       | Time-lapse of development progress            |

**Target length per clip:** 30–60 seconds

---

## 3. Store Listing

### App Name
- EN: {game_name}
- TR: {game_name}

### Short Description (80 chars max)
- EN: Tap, jump, survive — {game_name} is your next addictive mobile game.
- TR: Dokun, atla, hayatta kal — {game_name} yeni bağımlılık yapan mobil oyunun.

### Full Description (EN)
{game_name} is a {genre_label.lower()} mobile game designed for quick, addictive play sessions.

**Features:**
- Simple one-tap controls
- Endless gameplay with increasing difficulty
- Local high score system
- Smooth animations and satisfying sound effects
- Completely free to play

Challenge yourself and beat your own high score. How long can you last?

### Full Description (TR)
{game_name}, hızlı ve bağımlılık yapan oyun seansları için tasarlanmış bir {genre_label.lower()} mobil oyunudur.

**Özellikler:**
- Basit tek dokunuş kontrolleri
- Giderek zorlaşan sonsuz oynanış
- Yerel yüksek skor sistemi
- Akıcı animasyonlar ve tatmin edici ses efektleri
- Tamamen ücretsiz

Kendine meydan oku ve kendi rekoru kır. Ne kadar dayanabilirsin?

---

## 4. Keywords / ASO Tags

**EN:** {slug}, casual game, mobile game, tap game, endless game, high score, addictive, hyper-casual, free game, offline game

**TR:** {slug}, casual oyun, mobil oyun, dokunuş oyunu, sonsuz oyun, yüksek skor, bağımlılık yapan, hyper-casual, ücretsiz oyun, internetsiz oyun

---

## 5. Thumbnail Concepts

| Variant | Concept                                             | Colors              |
|---------|-----------------------------------------------------|---------------------|
| A       | Game character + logo on bold color background     | Brand primary color |
| B       | "Can you beat this?" text + gameplay screenshot    | High contrast       |
| C       | Score milestone visual + glowing effect            | Dark with neon      |

**Recommended size:** 1024x500 (Google Play Feature Graphic), 512x512 (icon)

---

## 6. Open Questions

- [ ] Final gameplay footage available for thumbnail?
- [ ] Developer name / studio name to show in video?
- [ ] Any platform-exclusive content (iOS vs Android)?
- [ ] Publishing date confirmed?

---

*This package was auto-generated by the Content Agent.
Review, edit, and approve before publishing.*
"""


class ContentAgent(BaseAgent):
    name = "content"

    def run(self, game_id: int) -> dict:
        """
        Full content phase:
        1. Generate content package markdown
        2. Create content tasks
        3. Create human review
        4. Update game content_status
        """
        game = self.get_game(game_id)
        if not game:
            raise ValueError(f"Game {game_id} not found")

        print(f"\n[content] Starting content phase for: {game['name']}")

        # 1. Generate and save content package
        content = _generate_content_package(game["name"], game.get("genre"))
        pkg_path = self._save_content_package(game["name"], content)
        print(f"[content] Content package saved: {pkg_path}")

        # 2. Update game content_status
        self.update_game_field(game_id, "content_status", "in_progress")

        # 3. Create tasks
        task1 = self.create_task(
            game_id,
            title="Content Package — Review & Finalize",
            description=f"Review the auto-generated content package for '{game['name']}'. Edit titles, descriptions, and video outline.\n\nFile: {pkg_path}",
            priority=1,
            review_required=True,
        )
        self.update_task_status(task1["id"], "review")

        task2 = self.create_task(
            game_id,
            title="Record YouTube long-form footage",
            description="Record gameplay and commentary following the video outline in the content package.",
            priority=2,
        )

        task3 = self.create_task(
            game_id,
            title="Create short-form clips (5x)",
            description="Record or clip 5 short-form videos from gameplay footage. Follow concepts in content package.",
            priority=2,
        )

        task4 = self.create_task(
            game_id,
            title="Design thumbnails (3 variants)",
            description="Create 3 thumbnail variants as described in the content package. Export as PNG.",
            priority=3,
        )

        task5 = self.create_task(
            game_id,
            title="Finalize store listing copy",
            description="Review and finalize EN + TR store listing text, keywords, and short description.",
            priority=3,
        )

        # 4. Create human review
        review = self.create_review(
            game_id,
            review_type="content_direction_approval",
            task_id=task1["id"],
            notes=f"Content package for '{game['name']}' is ready for review. Approve to proceed with production.",
        )

        return {
            "status": "content_phase_started",
            "game_id": game_id,
            "game_name": game["name"],
            "content_package_path": str(pkg_path),
            "tasks_created": [task1["id"], task2["id"], task3["id"], task4["id"], task5["id"]],
            "review_id": review["id"],
        }

    def _save_content_package(self, game_name: str, content: str) -> Path:
        slug = game_name.lower().replace(" ", "-")
        content_dir = Path(__file__).parent.parent.parent / "content" / slug
        content_dir.mkdir(parents=True, exist_ok=True)
        pkg_path = content_dir / "content-package.md"
        pkg_path.write_text(content, encoding="utf-8")
        return pkg_path
