"""
Game Design Agent — generates Mini Design Documents and design tasks.
Template-based (no LLM required). LLM hook is prepared for Phase 2+.
"""

import os
from pathlib import Path
from backend.agents.base_agent import BaseAgent

# Where MDD files are saved
GAMES_DIR = Path(__file__).parent.parent.parent / "games"

# ------------------------------------------------------------------ #
# MDD template library
# ------------------------------------------------------------------ #

GENRE_TEMPLATES = {
    "casual": {
        "session_length": "1–3 minutes",
        "controls": "Single tap / swipe",
        "win_condition": "Endless — high score system",
        "monetization": "Banner ads + optional rewarded video",
        "visual_style": "Minimalist flat design, bright colors",
    },
    "puzzle": {
        "session_length": "3–10 minutes",
        "controls": "Drag / tap to move pieces",
        "win_condition": "Complete the puzzle level",
        "monetization": "Level pack IAP + hint ads",
        "visual_style": "Clean UI, relaxing palette",
    },
    "arcade": {
        "session_length": "30 seconds – 2 minutes",
        "controls": "Tap or swipe for actions",
        "win_condition": "Survive as long as possible",
        "monetization": "Rewarded video for extra lives",
        "visual_style": "Bold retro or neon style",
    },
    "runner": {
        "session_length": "1–5 minutes",
        "controls": "Tap to jump / swipe to dodge",
        "win_condition": "Endless — distance/score based",
        "monetization": "Rewarded video + character skins IAP",
        "visual_style": "Dynamic parallax backgrounds",
    },
}

DEFAULT_TEMPLATE = {
    "session_length": "1–5 minutes",
    "controls": "Tap / swipe",
    "win_condition": "Score-based or level-based",
    "monetization": "Ads + optional IAP",
    "visual_style": "Clean mobile-friendly UI",
}


def _get_template(genre: str | None) -> dict:
    if not genre:
        return DEFAULT_TEMPLATE
    return GENRE_TEMPLATES.get(genre.lower().strip(), DEFAULT_TEMPLATE)


def _generate_mdd(game_name: str, genre: str | None) -> str:
    t = _get_template(genre)
    genre_label = genre.title() if genre else "Hyper-casual"
    slug = game_name.lower().replace(" ", "-")

    return f"""# Mini Design Document: {game_name}

**Generated by:** Game Design Agent (template-based)
**Status:** Draft — awaiting human review

---

## 1. Game Overview

| Field            | Value                          |
|------------------|-------------------------------|
| Title            | {game_name}                   |
| Genre            | {genre_label}                 |
| Platform         | Mobile (iOS + Android)        |
| Session Length   | {t['session_length']}         |
| Target Audience  | Casual gamers, 13+            |

---

## 2. Core Game Loop

1. Player opens the game → immediately starts playing
2. Core mechanic triggers (tap / interact)
3. Score or progress increases
4. Fail state reached → retry or continue
5. Loop repeats with increasing difficulty

---

## 3. Controls

{t['controls']}

---

## 4. Win & Fail Conditions

- **Win:** {t['win_condition']}
- **Fail:** Player makes a mistake or time runs out

---

## 5. Core Mechanics

- Primary mechanic: timing / reaction based interaction
- Difficulty: gradually increases each session
- Feedback: visual + haptic on success/fail
- Progression: score milestone rewards

---

## 6. Visual Style

{t['visual_style']}

---

## 7. MVP Scope

- [ ] 1 core mechanic implemented
- [ ] Endless mode
- [ ] Local high score storage
- [ ] Basic particle / juice effects
- [ ] Game Over screen with retry
- [ ] Main menu

**Out of MVP scope:**
- Multiplayer
- Cloud save
- Daily challenges
- Advanced analytics

---

## 8. Monetization Plan

{t['monetization']}

---

## 9. Content Plan

- 1 long-form YouTube video (gameplay + commentary)
- 3–5 short-form clips (TikTok / Reels / Shorts)
- Store listing: EN + TR
- Thumbnail: 3 concept variants

---

## 10. Open Questions

- [ ] What is the exact fail condition? (clarify with Build Agent)
- [ ] What difficulty curve to use? (linear / exponential)
- [ ] Any special platform-specific features (haptics, leaderboards)?

---

*This document was auto-generated by the Game Design Agent.
Review, edit, and approve before handing off to the Build Agent.*
"""


class GameDesignAgent(BaseAgent):
    name = "game_design"

    def run(self, game_id: int) -> dict:
        """
        Full design phase run for a given game:
        1. Load game from DB
        2. Generate MDD markdown file
        3. Create design tasks
        4. Create human review request
        5. Update game phase
        """
        game = self.get_game(game_id)
        if not game:
            raise ValueError(f"Game {game_id} not found")

        print(f"\n[game_design] Starting design phase for: {game['name']}")

        # 1. Generate MDD
        mdd_content = _generate_mdd(game["name"], game.get("genre"))
        mdd_path = self._save_mdd(game["name"], mdd_content)
        print(f"[game_design] MDD saved: {mdd_path}")

        # 2. Update game phase
        self.update_game_phase(game_id, "design_in_progress")

        # 3. Create tasks
        task1 = self.create_task(
            game_id,
            title="Mini Design Document — Review & Finalize",
            description=f"Review the auto-generated MDD for '{game['name']}'. Edit and approve before Build Agent handoff.\n\nFile: {mdd_path}",
            priority=1,
            review_required=True,
        )
        self.update_task_status(task1["id"], "review")

        task2 = self.create_task(
            game_id,
            title="Define Core Game Loop",
            description="Confirm: exact fail condition, difficulty curve, session feel. Update MDD section 2 if needed.",
            priority=2,
        )

        task3 = self.create_task(
            game_id,
            title="Clarify Open Questions in MDD",
            description="Answer the open questions listed in section 10 of the MDD.",
            priority=3,
        )

        # 4. Create human review
        review = self.create_review(
            game_id,
            review_type="design_document_approval",
            task_id=task1["id"],
            notes=f"Mini Design Document for '{game['name']}' is ready for review. Approve to hand off to Build Agent.",
        )

        return {
            "status": "design_phase_started",
            "game_id": game_id,
            "game_name": game["name"],
            "mdd_path": str(mdd_path),
            "tasks_created": [task1["id"], task2["id"], task3["id"]],
            "review_id": review["id"],
        }

    def _save_mdd(self, game_name: str, content: str) -> Path:
        slug = game_name.lower().replace(" ", "-")
        game_dir = GAMES_DIR / slug
        game_dir.mkdir(parents=True, exist_ok=True)
        mdd_path = game_dir / "mini-design-document.md"
        mdd_path.write_text(content, encoding="utf-8")
        return mdd_path
